[package]
name = "rust-frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
gloo = "0.11"
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = "0.3.70"